name: Create and invoke release in Digital.ai Release

description: A GitHub Action to create a new release and invoke from a template.

inputs:
  ReleaseServerAddress:
    description: 'The address of the release server.'
    required: true
  username:
    description: 'Username for authentication.'
    required: true
  password:
    description: 'Password for authentication.'
    required: true
  templateId:
    description: 'The ID of the template.'
    required: true
  releaseTitle:
    description: 'Title of the release.'
    required: false
  variables:
    description: 'JSON string representing the variables object.'
    required: false


runs:
  using: 'node20'
  main: 'dist/index.js'

author:
  name: 'Digital.ai'
  email: 'your@email.com'
