name: Digital.ai Release Integration
description: Github Actions for Digital.ai Release
author: Digital.ai
branding:
  color: "green"
  icon: "package"

inputs:
  serverUrl:
    description: 'The address of the Digital.ai Release server.'
    required: true
  username:
    description: 'Username for authentication to the Digital.ai Release server. Required if `token` is not provided.'
    required: false
  password:
    description: 'Password for authentication to the Digital.ai Release server. Required if `token` is not provided.'
    required: false
  token:
    description: 'Personal access token for authentication to the Digital.ai Release server. If provided, `username` and `password` are not required.'
    required: false
  templateId:
    description: 'The full template identifier in Digital.ai Release.'
    required: true
  releaseTitle:
    description: 'Optional. Title of the release. If not provided, a default title will be assigned.'
    required: false
  variables:
    description: 'Optional. JSON string representing the variables object to be passed to the release template.'
    required: false
  startRelease:
    description: 'Optional. Boolean value indicating whether to start the release. Default is true.'
    required: false
    default: 'true'

outputs:
  response:
    description: 'The response containing the data of the newly created release.'
  id:
    description: 'The id of the newly created release.'
  status:
    description: 'The status of the newly created release.' 

runs:
  using: 'node20'
  main: 'dist/index.js'

