name: Create and Start Release

on: [push]

jobs:
    create-and-start-release:
      runs-on: ubuntu-latest
      steps:

        - name: Create & Start Release
          id: release
          uses: digital-ai/github-actions-release@main
          with:
            serverUrl: 'http://digital-ai-release-server-url:5516'
            username: ${{ secrets.RELEASE_USERNAME }}
            password: ${{ secrets.RELEASE_PASSWORD }}
            templateId: 'Applications/Folder3f5cf31df1544/Releasec4e4b7bce46f4720a'
            releaseTitle: 'New Release from GitHub Actions'
            variables: '{"var1": "value1", "var2": "value2"}'
            startRelease: true

        - name: Get Release Data
          run: echo ${{ steps.release.outputs.response }}

        - name: Get Release Id
          run: echo ${{ steps.release.outputs.id }}
        
        - name: Get Release Status
          run: echo ${{ steps.release.outputs.status }}          