name: GitHub Actions Test

on: [workflow_dispatch]

jobs:
    create-release:
      runs-on: ubuntu-latest
      steps:

        - name: Checkout
          uses: actions/checkout@v4

        - name: Create & Start Release
          id: release
          uses: ./
          with:
            serverUrl: ${{ secrets.SERVERURL }}
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.PASSWORD }}
            templateId: 'Applications/Folder3f5cf31df154440495d8af9425aa9cdb/Releasec4e4b7bce46f4720a43ead5da8543086'
            variables: '{"var1": "Digital.ai"}'
            releaseTitle: 'New Release from GitHub Actions'

        - name: Get Release Id
          run: echo ${{ steps.release.outputs.id }}
        
        - name: Get Release Status
          run: echo ${{ steps.release.outputs.status }}