name: Create Release

on: [workflow_dispatch]

jobs:
    create-release:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
       
        - name: Create Release
          uses: ./
          with:
            ReleaseServerAddress: ${{ secrets.ReleaseServerAddress }}
            username: ${{ secrets.username }}
            password: ${{ secrets.password }}
            templateId: ${{ secrets.templateId }}
            