name: Create Release

on: [workflow_dispatch]

jobs:
    create-release:
      runs-on: ubuntu-latest
      steps:
       
        - name: Checkout
          uses: actions/checkout@v4
        - name: Create Release
          uses: ./
          with:
            serverUrl: 'http://65.2.30.53:5516'
            token: ${{ secrets.token }}
            templateId: 'Folder3f5cf31df154440495d8af9425aa9cdb/Releasec4e4b7bce46f4720a43ead5da8543086'
            variables: '{"var1": "Two"}' 
            releaseTitle: 'Action'
        - name: Extract tag name
          run: echo "Tag name is ${GITHUB_REF#refs/tags/}"