name: Create Release

on: [workflow_dispatch]

jobs:
    create-release:
      runs-on: ubuntu-latest
      steps:
       
        - name: Checkout
          uses: actions/checkout@v4
        - name: Create Release
          uses: ./
          with:
            serverUrl: 'http://65.2.30.53:5516'
            username: ${{ secrets.username }}
            password: ${{ secrets.password }}
            templateId: ${{ secrets.templateId }}
            variables: '{"var1": "Two"}' 
            