name: Run unit tests

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        uses: bahmutov/npm-install@v1

      - name: Test
        run: npm run test